//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_Motorbike_44K21108.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BMEntities1 : DbContext
    {
        public BMEntities1()
            : base("name=BMEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        internal IEnumerable<T> Query<T>(string v, string a)
        {
            throw new NotImplementedException();
        }

        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<HOADON_CT> HOADON_CT { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<XE> XEs { get; set; }
    }
}
