//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_Motorbike_44K21108.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON_CT
    {
        public string MaHD { get; set; }
        public string MaXe { get; set; }
        public string MaNCC { get; set; }
        public int Soluong { get; set; }
        public int ThanhTien { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual XE XE { get; set; }
    }
}
