//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_Motorbike_44K21108.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.HOADON_CT = new HashSet<HOADON_CT>();
        }
    
        public string MaXe { get; set; }
        public string LoaiXe { get; set; }
        public string TenXe { get; set; }
        public string BienSo { get; set; }
        public int GiaXe { get; set; }
        public bool TrangThai { get; set; }
        public string HinhAnh { get; set; }
        public string ThongTin { get; set; }
        public string MaNCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON_CT> HOADON_CT { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
